exec:  "/usr/local/bin/litestream replicate" 

fuse:
  dir: "/litfs"
  allow-other: true

# proxy:
#   addr: ":8080"
#   target: "localhost:8090"
#   db: "data.db"

http:
  addr: ":20202"

data:
  dir: "/var/lib/litefs"

lease:
  # Required. Must be either "consul" or "static".
  type: "static"

  # Required. The URL for the primary node's LiteFS API.
  # Note: replace `primary` with the appropriate hostname for your primary node!
  advertise-url: "http://0.0.0.0:20202"

  # Specifies whether the node can become the primary. If using
  # "static" leasing, this should be set to true on the primary
  # and false on the replicas.
  # Note: update this to `false` on the replica nodes!
  candidate: true